// tslint:disable
/**
 * Copyright 2022 Splunk, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"): you may
 * not use this file except in compliance with the License. You may obtain
 * a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 * App Registry
 * With the App Registry service in Splunk Cloud Services, you can create, update, and manage your apps.
 *
 * OpenAPI spec version: v1beta2.0 (recommended default)
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AppMetadataPublic
 */
export interface AppMetadataPublic {
    /**
     * Array of permission templates that are used to grant permission to the app principal when a tenant subscribes.
     * @type {Array<string>}
     * @memberof AppMetadataPublic
     */
    appPrincipalPermissions?: Array<string>;

    /**
     * Short paragraph describing the app.
     * @type {string}
     * @memberof AppMetadataPublic
     */
    description?: string;

    /**
     * The URL used to log in to the app.
     * @type {string}
     * @memberof AppMetadataPublic
     */
    loginUrl?: string;

    /**
     * The URL used to display the app's logo.
     * @type {string}
     * @memberof AppMetadataPublic
     */
    logoUrl?: string;

    /**
     * Human-readable title for the app.
     * @type {string}
     * @memberof AppMetadataPublic
     */
    title?: string;

    /**
     * Array of permission filter templates that are used to intersect with a user's permissions when using the app.
     * @type {Array<string>}
     * @memberof AppMetadataPublic
     */
    userPermissionsFilter?: Array<string>;

}

