// tslint:disable
/**
 * Copyright 2022 Splunk, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"): you may
 * not use this file except in compliance with the License. You may obtain
 * a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 * Search Catalog service
 * With the Metadata Catalog in Splunk Cloud Services you can create and manage knowledge objects such as datasets, fields, rules, actions, and dashboards.
 *
 * OpenAPI spec version: v2beta1.4 (recommended default)
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    FieldPOST,
    JobDatasetKind,
    JobDatasetPropertiesTimelineMetadata,
} from './';

/**
 * Job dataset as rendered in POST response for dataset API endpoint.
 * @export
 * @interface JobDatasetGET
 */
export interface JobDatasetGET {
    /**
     * Time that the job was completed
     * @type {string}
     * @memberof JobDatasetGET
     */
    completionTime: string;

    /**
     * The time the dataset will be available in S3.
     * @type {string}
     * @memberof JobDatasetGET
     */
    deleteTime: string;

    /**
     * Time that the job was dispatched
     * @type {string}
     * @memberof JobDatasetGET
     */
    dispatchTime: string;

    /**
     * 
     * @type {JobDatasetKind}
     * @memberof JobDatasetGET
     */
    kind: JobDatasetKind;

    /**
     * The dataset name. Dataset names must be unique within each module.
     * @type {string}
     * @memberof JobDatasetGET
     */
    name: string;

    /**
     * Parameters for the search job, mainly earliest, latest, timezone, and relativeTimeAnchor.
     * @type {{ [key: string]: any; }}
     * @memberof JobDatasetGET
     */
    parameters: { [key: string]: any; };

    /**
     * The SPL query string for the search job.
     * @type {string}
     * @memberof JobDatasetGET
     */
    query: string;

    /**
     * Resolved earliest time for the job
     * @type {string}
     * @memberof JobDatasetGET
     */
    resolvedEarliest: string;

    /**
     * Resolved latest time for the job
     * @type {string}
     * @memberof JobDatasetGET
     */
    resolvedLatest: string;

    /**
     * The ID assigned to the search job.
     * @type {string}
     * @memberof JobDatasetGET
     */
    sid: string;

    /**
     * Was the event summary requested for this searhc job?
     * @type {boolean}
     * @memberof JobDatasetGET
     */
    collectEventSummary?: boolean;

    /**
     * Was the field summary requested for this searhc job?
     * @type {boolean}
     * @memberof JobDatasetGET
     */
    collectFieldSummary?: boolean;

    /**
     * Were the time bucketes requested for this searhc job?
     * @type {boolean}
     * @memberof JobDatasetGET
     */
    collectTimeBuckets?: boolean;

    /**
     * Specifies whether a search is allowed to collect preview results during the runtime, internal search service use only.
     * @type {boolean}
     * @memberof JobDatasetGET
     */
    enablePreview?: boolean;

    /**
     * The runtime of the search in seconds.
     * @type {number}
     * @memberof JobDatasetGET
     */
    executionTime?: number;

    /**
     * Should the search produce all fields (including those not explicity mentioned in the SPL)?
     * @type {boolean}
     * @memberof JobDatasetGET
     */
    extractAllFields?: boolean;

    /**
     * The fields to extract. Valid values are all, none, or indexed.
     * @type {string}
     * @memberof JobDatasetGET
     */
    extractFields?: string;

    /**
     * The fields to be associated with this dataset.
     * @type {Array<FieldPOST>}
     * @memberof JobDatasetGET
     */
    fields?: Array<FieldPOST>;

    /**
     * Did the SPL query cause any side effects on a dataset?
     * @type {boolean}
     * @memberof JobDatasetGET
     */
    hasSideEffects?: boolean;

    /**
     * A unique dataset ID. Random ID used if not provided.
     * @type {string}
     * @memberof JobDatasetGET
     */
    id?: string;

    /**
     * The maximum number of seconds to run this search before finishing.
     * @type {number}
     * @memberof JobDatasetGET
     */
    maxTime?: number;

    /**
     * Array of json objects to store critical search job messages.
     * @type {Array<{ [key: string]: any; }>}
     * @memberof JobDatasetGET
     */
    messages?: Array<{ [key: string]: any; }>;

    /**
     * The name of the module to create the new dataset in.
     * @type {string}
     * @memberof JobDatasetGET
     */
    module?: string;

    /**
     * The parent's ID of the search job.
     * @type {string}
     * @memberof JobDatasetGET
     */
    parent?: string;

    /**
     * An estimate of how complete the search job is.
     * @type {number}
     * @memberof JobDatasetGET
     */
    percentComplete?: number;

    /**
     * The instantaneous number of results produced by the search job.
     * @type {number}
     * @memberof JobDatasetGET
     */
    resultsAvailable?: number;

    /**
     * The search head that started this search job.
     * @type {string}
     * @memberof JobDatasetGET
     */
    searchHead?: string;

    /**
     * The SPLv2 version of the search job query string.
     * @type {string}
     * @memberof JobDatasetGET
     */
    spl?: string;

    /**
     * The current status of the search job.
     * @type {string}
     * @memberof JobDatasetGET
     */
    status?: string;

    /**
     * 
     * @type {JobDatasetPropertiesTimelineMetadata}
     * @memberof JobDatasetGET
     */
    timelineMetadata?: JobDatasetPropertiesTimelineMetadata;

}

