// tslint:disable
/**
 * Copyright 2022 Splunk, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"): you may
 * not use this file except in compliance with the License. You may obtain
 * a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 * Metadata Catalog
 * With the Metadata Catalog you can create and manage knowledge objects such as datasets, fields, rules, actions, dashboards, and workflows.
 *
 * OpenAPI spec version: v2alpha2.6 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A complete workflow run as rendered in POST, PATCH, and GET responses.
 * @export
 * @interface WorkflowRun
 */
export interface WorkflowRun {
    /**
     * The date and time the workflow run was created.
     * @type {string}
     * @memberof WorkflowRun
     */
    created: string;

    /**
     * The name of the user who created the workflow run. This value is obtained from the bearer token and may not be changed.
     * @type {string}
     * @memberof WorkflowRun
     */
    createdby: string;

    /**
     * A unique workflow Run ID.
     * @type {string}
     * @memberof WorkflowRun
     */
    id: string;

    /**
     * The input data of the workflow run.
     * @type {Array<string>}
     * @memberof WorkflowRun
     */
    inputdata: Array<string>;

    /**
     * The output data of the workflow run.
     * @type {Array<string>}
     * @memberof WorkflowRun
     */
    outputdata: Array<string>;

    /**
     * The name of the workflow run's owner.
     * @type {string}
     * @memberof WorkflowRun
     */
    owner: string;

    /**
     * The timeout in seconds of the workflow.
     * @type {number}
     * @memberof WorkflowRun
     */
    timeoutsecs: number;

    /**
     * A unique workflow build ID that is associated with the workflow run.
     * @type {string}
     * @memberof WorkflowRun
     */
    workflowbuildid: string;

    /**
     * The version of the workflow build that is associated with the workflow run.
     * @type {number}
     * @memberof WorkflowRun
     */
    workflowbuildversion: number;

    /**
     * The description of the workflow run.
     * @type {string}
     * @memberof WorkflowRun
     */
    description?: string;

    /**
     * The date and time the workflow build ended.
     * @type {string}
     * @memberof WorkflowRun
     */
    ended?: string;

    /**
     * The failure message of the workflow run.
     * @type {string}
     * @memberof WorkflowRun
     */
    failuremessage?: string;

    /**
     * The workflow run name.
     * @type {string}
     * @memberof WorkflowRun
     */
    name?: string;

    /**
     * The date and time the workflow build started.
     * @type {string}
     * @memberof WorkflowRun
     */
    started?: string;

    /**
     * The status of the workflow run.
     * @type {string}
     * @memberof WorkflowRun
     */
    status?: string;

}

