// tslint:disable
/**
 * Copyright 2019 Splunk, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"): you may
 * not use this file except in compliance with the License. You may obtain
 * a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 * Metadata Catalog
 * With the Metadata Catalog you can create and manage knowledge objects such as datasets, fields, rules, actions, dashboards, and workflows.
 *
 * OpenAPI spec version: v2alpha2.6 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    RecurringSearchDatasetKind,
    RecurringSearchDatasetPropertiesQueryParameters,
} from './';

/**
 * A complete recurringsearch dataset as rendered in POST, PATCH, and GET responses.
 * @export
 * @interface RecurringSearchDataset
 */
export interface RecurringSearchDataset {
    /**
     * The date and time object was created.
     * @type {string}
     * @memberof RecurringSearchDataset
     */
    readonly created: string;

    /**
     * The name of the user who created the object. This value is obtained from the bearer token and may not be changed.
     * @type {string}
     * @memberof RecurringSearchDataset
     */
    readonly createdby: string;

    /**
     * A unique dataset ID.
     * @type {string}
     * @memberof RecurringSearchDataset
     */
    id: string;

    /**
     * The recurrence interval.
     * @type {string}
     * @memberof RecurringSearchDataset
     */
    interval: string;

    /**
     * 
     * @type {RecurringSearchDatasetKind}
     * @memberof RecurringSearchDataset
     */
    kind: RecurringSearchDatasetKind;

    /**
     * The date and time object was modified.
     * @type {string}
     * @memberof RecurringSearchDataset
     */
    readonly modified: string;

    /**
     * The name of the user who most recently modified the object.
     * @type {string}
     * @memberof RecurringSearchDataset
     */
    readonly modifiedby: string;

    /**
     * The name of the module that contains the dataset.
     * @type {string}
     * @memberof RecurringSearchDataset
     */
    module: string;

    /**
     * The dataset name. Dataset names must be unique within each module.
     * @type {string}
     * @memberof RecurringSearchDataset
     */
    name: string;

    /**
     * The name of the object's owner.
     * @type {string}
     * @memberof RecurringSearchDataset
     */
    readonly owner: string;

    /**
     * A valid SPL.
     * @type {string}
     * @memberof RecurringSearchDataset
     */
    query: string;

    /**
     * The dataset name qualified by the module name.
     * @type {string}
     * @memberof RecurringSearchDataset
     */
    resourcename: string;

    /**
     * An application name.
     * @type {string}
     * @memberof RecurringSearchDataset
     */
    app?: string;

    /**
     * Detailed description of the dataset.
     * @type {string}
     * @memberof RecurringSearchDataset
     */
    description?: string;

    /**
     * Specifies whether or not the recurringsearch is disabled.
     * @type {boolean}
     * @memberof RecurringSearchDataset
     */
    enabled?: boolean;

    /**
     * The sid of the most recently run search job.
     * @type {string}
     * @memberof RecurringSearchDataset
     */
    mostRecentSid?: string;

    /**
     * The next execution time in epoch time.
     * @type {number}
     * @memberof RecurringSearchDataset
     */
    nextExecutionTime?: number;

    /**
     * 
     * @type {RecurringSearchDatasetPropertiesQueryParameters}
     * @memberof RecurringSearchDataset
     */
    queryParameters?: RecurringSearchDatasetPropertiesQueryParameters;

    /**
     * The name of the user whom a search will be run as.
     * @type {string}
     * @memberof RecurringSearchDataset
     */
    runAs?: string;

    /**
     * The offset in minutes that delays the dispatch time.
     * @type {number}
     * @memberof RecurringSearchDataset
     */
    skew?: number;

    /**
     * Summary of the dataset's purpose.
     * @type {string}
     * @memberof RecurringSearchDataset
     */
    summary?: string;

    /**
     * The title of the dataset.  Does not have to be unique.
     * @type {string}
     * @memberof RecurringSearchDataset
     */
    title?: string;

    /**
     * The catalog version.
     * @type {number}
     * @memberof RecurringSearchDataset
     */
    version?: number;

}

