// tslint:disable
/**
 * Copyright 2022 Splunk, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"): you may
 * not use this file except in compliance with the License. You may obtain
 * a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 * Metadata Catalog
 * With the Metadata Catalog you can create and manage knowledge objects such as datasets, fields, rules, actions, dashboards, and workflows.
 *
 * OpenAPI spec version: v2alpha2.6 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    RegexActionKind,
} from './';

/**
 * A complete regex action as rendered in POST, PATCH, and GET responses.
 * @export
 * @interface RegexAction
 */
export interface RegexAction {
    /**
     * The date and time object was created.
     * @type {string}
     * @memberof RegexAction
     */
    readonly created: string;

    /**
     * The name of the user who created the object. This value is obtained from the bearer token and may not be changed.
     * @type {string}
     * @memberof RegexAction
     */
    readonly createdby: string;

    /**
     * Name of the field that is matched against the regular expression.
     * @type {string}
     * @memberof RegexAction
     */
    field: string;

    /**
     * A unique action ID.
     * @type {string}
     * @memberof RegexAction
     */
    id: string;

    /**
     * 
     * @type {RegexActionKind}
     * @memberof RegexAction
     */
    kind: RegexActionKind;

    /**
     * The date and time object was modified.
     * @type {string}
     * @memberof RegexAction
     */
    readonly modified: string;

    /**
     * The name of the user who most recently modified the object.
     * @type {string}
     * @memberof RegexAction
     */
    readonly modifiedby: string;

    /**
     * The name of the object's owner.
     * @type {string}
     * @memberof RegexAction
     */
    readonly owner: string;

    /**
     * A regular expression that includes named capture groups for the purpose of field extraction.
     * @type {string}
     * @memberof RegexAction
     */
    pattern: string;

    /**
     * The rule that this action is part of.
     * @type {string}
     * @memberof RegexAction
     */
    ruleid: string;

    /**
     * AppClinetId of the creator app of the dataset.
     * @type {string}
     * @memberof RegexAction
     */
    appclientidcreatedby?: string;

    /**
     * AppClinetId of the modifier app of the dataset.
     * @type {string}
     * @memberof RegexAction
     */
    appclientidmodifiedby?: string;

    /**
     * The maximum number of times per event to attempt to match fields with the regular expression.
     * @type {number}
     * @memberof RegexAction
     */
    limit?: number;

    /**
     * The catalog version.
     * @type {number}
     * @memberof RegexAction
     */
    version?: number;

}

