// tslint:disable
/**
 * Copyright 2019 Splunk, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"): you may
 * not use this file except in compliance with the License. You may obtain
 * a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 * Metadata Catalog
 * With the Metadata Catalog you can create and manage knowledge objects such as datasets, fields, rules, actions, dashboards, and workflows.
 *
 * OpenAPI spec version: v2alpha2.6 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    RecurringSearchDatasetKind,
    RecurringSearchDatasetPropertiesQueryParameters,
} from './';

/**
 * Properties of recurringsearch datasets which may be read, set, and changed through the API. Implementation detail of DatasetPOST, DatasetPATCH, and Dataset, do not use directly.
 * @export
 * @interface RecurringSearchDatasetProperties
 */
export interface RecurringSearchDatasetProperties {
    /**
     * An application name.
     * @type {string}
     * @memberof RecurringSearchDatasetProperties
     */
    app?: string;

    /**
     * Specifies whether or not the recurringsearch is disabled.
     * @type {boolean}
     * @memberof RecurringSearchDatasetProperties
     */
    enabled?: boolean;

    /**
     * The recurrence interval.
     * @type {string}
     * @memberof RecurringSearchDatasetProperties
     */
    interval?: string;

    /**
     * 
     * @type {RecurringSearchDatasetKind}
     * @memberof RecurringSearchDatasetProperties
     */
    kind?: RecurringSearchDatasetKind;

    /**
     * The sid of the most recently run search job.
     * @type {string}
     * @memberof RecurringSearchDatasetProperties
     */
    mostRecentSid?: string;

    /**
     * The next execution time in epoch time.
     * @type {number}
     * @memberof RecurringSearchDatasetProperties
     */
    nextExecutionTime?: number;

    /**
     * A valid SPL.
     * @type {string}
     * @memberof RecurringSearchDatasetProperties
     */
    query?: string;

    /**
     * 
     * @type {RecurringSearchDatasetPropertiesQueryParameters}
     * @memberof RecurringSearchDatasetProperties
     */
    queryParameters?: RecurringSearchDatasetPropertiesQueryParameters;

    /**
     * The name of the user whom a search will be run as.
     * @type {string}
     * @memberof RecurringSearchDatasetProperties
     */
    runAs?: string;

    /**
     * The offset in minutes that delays the dispatch time.
     * @type {number}
     * @memberof RecurringSearchDatasetProperties
     */
    skew?: number;

}

