// tslint:disable
/**
 * Copyright 2020 Splunk, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"): you may
 * not use this file except in compliance with the License. You may obtain
 * a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 * Machine Learning
 * Use the Machine Learning service in Splunk Cloud Services to deliver resource intensive machine learning workloads. The Machine Learning service covers model experimentation, training, inference, validation, scoring, and serving.
 *
 * OpenAPI spec version: v2beta1.1 (recommended default)
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    InputData,
    OutputData,
    Score,
    TaskSummary,
    Workflow,
    WorkflowBuildValidationOption,
    WorkflowBuildValidationScore,
} from './';

/**
 *
 * @export
 * @interface WorkflowBuild
 */
export interface WorkflowBuild {
    /**
     * 
     * @type {InputData}
     * @memberof WorkflowBuild
     */
    input: InputData;

    /**
     * 
     * @type {string}
     * @memberof WorkflowBuild
     */
    readonly creationTime?: string;

    /**
     * 
     * @type {string}
     * @memberof WorkflowBuild
     */
    readonly endTime?: string;

    /**
     * 
     * @type {string}
     * @memberof WorkflowBuild
     */
    readonly id?: string;

    /**
     * 
     * @type {string}
     * @memberof WorkflowBuild
     */
    name?: string;

    /**
     * 
     * @type {OutputData}
     * @memberof WorkflowBuild
     */
    output?: OutputData;

    /**
     * 
     * @type {Array<TaskSummary>}
     * @memberof WorkflowBuild
     */
    readonly pipelineSummary?: Array<TaskSummary>;

    /**
     * 
     * @type {string}
     * @memberof WorkflowBuild
     */
    readonly startTime?: string;

    /**
     * 
     * @type {string}
     * @memberof WorkflowBuild
     */
    readonly status?: WorkflowBuildStatusEnum;

    /**
     * Number of seconds before a workflow build times out.
     * @type {number}
     * @memberof WorkflowBuild
     */
    timeoutSecs?: number;

    /**
     * 
     * @type {Score}
     * @memberof WorkflowBuild
     */
    trainingScore?: Score;

    /**
     * 
     * @type {WorkflowBuildValidationOption}
     * @memberof WorkflowBuild
     */
    validationOption?: WorkflowBuildValidationOption;

    /**
     * 
     * @type {WorkflowBuildValidationScore}
     * @memberof WorkflowBuild
     */
    validationScore?: WorkflowBuildValidationScore;

    /**
     * 
     * @type {Workflow}
     * @memberof WorkflowBuild
     */
    workflow?: Workflow;

}

/**
 * @export
 */
export enum WorkflowBuildStatusEnum {
    Running = 'running',
    Failed = 'failed',
    Success = 'success',
    Scheduled = 'scheduled'
}

