/**
 * Action Service
 * A service that receives incoming notifications and uses pre-defined templates (action objects) to turn those notifications into meaningful actions.
 *
 * OpenAPI spec version: v1beta2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface Action
 */
export interface Action {
    /**
     * The name of the action. The name is one or more identifier strings separated by dots. Each identifier string consists of lower case letters, digits, and underscores, and cannot start with a digit.
     * @type {string}
     * @memberof Action
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof Action
     */
    kind: Action.KindEnum;
    /**
     * Human readable name title for the action. Must be less than 128 characters.
     * @type {string}
     * @memberof Action
     */
    title?: string;
    /**
     *
     * @type {string}
     * @memberof Action
     */
    subject?: string;
    /**
     *
     * @type {string}
     * @memberof Action
     */
    body?: string;
    /**
     *
     * @type {Array<string>}
     * @memberof Action
     */
    addresses?: Array<string>;
    /**
     * Only allows the HTTPS scheme.
     * @type {string}
     * @memberof Action
     */
    webhookUrl?: string;
    /**
     * The (possibly) templated payload body which will be POSTed to the webhookUrl when triggered.
     * @type {string}
     * @memberof Action
     */
    webhookPayload?: string;
}
export declare function ActionFromJSON(json: any): Action;
export declare function ActionToJSON(value?: Action): any;
/**
 * @export
 * @namespace Action
 */
export declare namespace Action {
    /**
     * @export
     * @enum {string}
     */
    enum KindEnum {
        Webhook = "webhook",
        Email = "email"
    }
}
