/**
 * Action Service
 * A service that receives incoming notifications and uses pre-defined templates (action objects) to turn those notifications into meaningful actions.
 *
 * OpenAPI spec version: v1beta2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface ActionResult
 */
export interface ActionResult {
    /**
     *
     * @type {string}
     * @memberof ActionResult
     */
    state?: ActionResult.StateEnum;
    /**
     *
     * @type {string}
     * @memberof ActionResult
     */
    statusId: string;
    /**
     *
     * @type {string}
     * @memberof ActionResult
     */
    message?: string;
}
export declare function ActionResultFromJSON(json: any): ActionResult;
export declare function ActionResultToJSON(value?: ActionResult): any;
/**
 * @export
 * @namespace ActionResult
 */
export declare namespace ActionResult {
    /**
     * @export
     * @enum {string}
     */
    enum StateEnum {
        QUEUED = "QUEUED",
        RUNNING = "RUNNING",
        DONE = "DONE",
        FAILED = "FAILED"
    }
}
