// tslint:disable
/**
 * Action Service
 * A service that receives incoming notifications and uses pre-defined templates (action objects) to turn those notifications into meaningful actions.
 *
 * OpenAPI spec version: v1beta2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
import {
    ActionCommon,
    ActionCommonFromJSON,
    ActionCommonToJSON,
    EmailActionMutable,
    EmailActionMutableFromJSON,
    EmailActionMutableToJSON,
} from './';

/**
 * 
 * @export
 * @interface EmailAction
 */
export interface EmailAction {
    /**
     * The name of the action. The name is one or more identifier strings separated by dots. Each identifier string consists of lower case letters, digits, and underscores, and cannot start with a digit.
     * @type {string}
     * @memberof EmailAction
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof EmailAction
     */
    kind: EmailAction.KindEnum;
    /**
     * Human readable name title for the action. Must be less than 128 characters.
     * @type {string}
     * @memberof EmailAction
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof EmailAction
     */
    subject?: string;
    /**
     * 
     * @type {string}
     * @memberof EmailAction
     */
    body?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof EmailAction
     */
    addresses?: Array<string>;
}

export function EmailActionFromJSON(json: any): EmailAction {
    return {
    // TODO: Template Change
    } as EmailAction;

}

export function EmailActionToJSON(value?: EmailAction): any {
    if (value === undefined) {
        return undefined;
    }
    return {
    };
}

/**
 * @export
 * @namespace EmailAction
 */
export namespace EmailAction {
    /**
     * @export
     * @enum {string}
     */
    export enum KindEnum {
        Webhook = 'webhook',
        Email = 'email'
    }
}

