// tslint:disable
/**
 * Action Service
 * A service that receives incoming notifications and uses pre-defined templates (action objects) to turn those notifications into meaningful actions.
 *
 * OpenAPI spec version: v1beta2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
/**
 * 
 * @export
 * @interface ModelError
 */
export interface ModelError {
    /**
     * 
     * @type {string}
     * @memberof ModelError
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof ModelError
     */
    message: string;
    /**
     * 
     * @type {any}
     * @memberof ModelError
     */
    details?: any;
    /**
     * 
     * @type {string}
     * @memberof ModelError
     */
    moreInfo?: string;
}

export function ModelErrorFromJSON(json: any): ModelError {
    return {
        'code': json['code'],
        'message': json['message'],
        'details': !exists(json, 'details') ? undefined : anyFromJSON(json['details']),
        'moreInfo': !exists(json, 'moreInfo') ? undefined : json['moreInfo'],
    };
}

export function ModelErrorToJSON(value?: ModelError): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'code': value.code,
        'message': value.message,
        'details': anyToJSON(value.details),
        'moreInfo': value.moreInfo,
    };
}


