/**
 * Action Service
 * A service that receives incoming notifications and uses pre-defined templates (action objects) to turn those notifications into meaningful actions.
 *
 * OpenAPI spec version: v1beta2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface Notification
 */
export interface Notification {
    /**
     *
     * @type {any}
     * @memberof Notification
     */
    payload: any;
    /**
     *
     * @type {string}
     * @memberof Notification
     */
    tenant: string;
    /**
     *
     * @type {string}
     * @memberof Notification
     */
    kind: Notification.KindEnum;
}
export declare function NotificationFromJSON(json: any): Notification;
export declare function NotificationToJSON(value?: Notification): any;
/**
 * @export
 * @namespace Notification
 */
export declare namespace Notification {
    /**
     * @export
     * @enum {string}
     */
    enum KindEnum {
        SplunkEvent = "splunkEvent",
        RawJSON = "rawJSON"
    }
}
