"use strict";
// tslint:disable
/**
 * Action Service
 * A service that receives incoming notifications and uses pre-defined templates (action objects) to turn those notifications into meaningful actions.
 *
 * OpenAPI spec version: v1beta2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
function SplunkEventPayloadFromJSON(json) {
    return {
        // TODO: Template Change
        'event': JSON.parse(json['event']),
        // 'event': anyFromJSON(json['event']),
        'fields': json['fields'],
        'host': json['host'],
        'index': json['index'],
        'source': json['source'],
        'sourcetype': json['sourcetype'],
        'time': json['time'],
    };
}
exports.SplunkEventPayloadFromJSON = SplunkEventPayloadFromJSON;
function SplunkEventPayloadToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    return {
        // TODO: Template Change
        // Original
        // 'event': anyToJSON(value.event),
        // New
        'event': JSON.stringify(value.event),
        'fields': value.fields,
        'host': value.host,
        'index': value.index,
        'source': value.source,
        'sourcetype': value.sourcetype,
        'time': value.time,
    };
}
exports.SplunkEventPayloadToJSON = SplunkEventPayloadToJSON;
//# sourceMappingURL=SplunkEventPayload.js.map