// tslint:disable
/**
 * Copyright 2021 Splunk, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"): you may
 * not use this file except in compliance with the License. You may obtain
 * a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 * Splunk Search service
 * Use the Search service in Splunk Cloud Services to dispatch, review, and manage searches and search jobs. You can finalize or cancel jobs, retrieve search results, and request search-related configurations from the Metadata Catalog service in Splunk Cloud Services.
 *
 * OpenAPI spec version: v3alpha1 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Properties of metric datasets which can only be read through the API.
 * @export
 * @interface DatasetReadOnlyProperties
 */
export interface DatasetReadOnlyProperties {
    /**
     * The timestamp, in seconds, of the earliest measure. The timestamp is in UNIX time.
     * @type {string}
     * @memberof DatasetReadOnlyProperties
     */
    earliestEventTime?: string;

    /**
     * The earliest index time for any of the measures in this index.
     * @type {string}
     * @memberof DatasetReadOnlyProperties
     */
    earliestIngestTime?: string;

    /**
     * The timestamp, in seconds, of the latest measure. The timestamp is in UNIX time.
     * @type {string}
     * @memberof DatasetReadOnlyProperties
     */
    latestEventTime?: string;

    /**
     * The earliest index time for any of the measures in this index.
     * @type {string}
     * @memberof DatasetReadOnlyProperties
     */
    latestIngestTime?: string;

    /**
     * The latest time that the metric index metadata was refreshed.
     * @type {string}
     * @memberof DatasetReadOnlyProperties
     */
    latestMetadataUpdateTime?: string;

    /**
     * THe number of measures in the metric index.
     * @type {number}
     * @memberof DatasetReadOnlyProperties
     */
    totalEventCount?: number;

    /**
     * For metrics indexes, the totalSize is set to 0.
     * @type {number}
     * @memberof DatasetReadOnlyProperties
     */
    totalSize?: number;

}

