"use strict";
/**
 * Action Service
 * A service that receives incoming notifications and uses pre-defined templates (action objects) to turn those notifications into meaningful actions.
 *
 * OpenAPI spec version: v1beta2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var ActionResult = /** @class */ (function () {
    function ActionResult() {
    }
    ActionResult.getAttributeTypeMap = function () {
        return ActionResult.attributeTypeMap;
    };
    ActionResult.discriminator = undefined;
    ActionResult.attributeTypeMap = [
        {
            name: 'state',
            baseName: 'state',
            type: 'ActionResult.StateEnum',
        },
        {
            name: 'statusId',
            baseName: 'statusId',
            type: 'string',
        },
        {
            name: 'message',
            baseName: 'message',
            type: 'string',
        },
    ];
    return ActionResult;
}());
exports.ActionResult = ActionResult;
(function (ActionResult) {
    var StateEnum;
    (function (StateEnum) {
        StateEnum[StateEnum["QUEUED"] = 'QUEUED'] = "QUEUED";
        StateEnum[StateEnum["RUNNING"] = 'RUNNING'] = "RUNNING";
        StateEnum[StateEnum["DONE"] = 'DONE'] = "DONE";
        StateEnum[StateEnum["FAILED"] = 'FAILED'] = "FAILED";
    })(StateEnum = ActionResult.StateEnum || (ActionResult.StateEnum = {}));
})(ActionResult = exports.ActionResult || (exports.ActionResult = {}));
exports.ActionResult = ActionResult;
//# sourceMappingURL=actionResult.js.map