"use strict";
/**
 * Action Service
 * A service that receives incoming notifications and uses pre-defined templates (action objects) to turn those notifications into meaningful actions.
 *
 * OpenAPI spec version: v1beta2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var ActionMutableCommon = /** @class */ (function () {
    function ActionMutableCommon() {
    }
    ActionMutableCommon.getAttributeTypeMap = function () {
        return ActionMutableCommon.attributeTypeMap;
    };
    ActionMutableCommon.discriminator = undefined;
    ActionMutableCommon.attributeTypeMap = [
        {
            name: 'title',
            baseName: 'title',
            type: 'string',
        },
    ];
    return ActionMutableCommon;
}());
exports.ActionMutableCommon = ActionMutableCommon;
//# sourceMappingURL=actionMutableCommon.js.map