"use strict";
/**
 * Action Service
 * A service that receives incoming notifications and uses pre-defined templates (action objects) to turn those notifications into meaningful actions.
 *
 * OpenAPI spec version: v1beta2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var DeprecatedAction = /** @class */ (function () {
    function DeprecatedAction() {
    }
    DeprecatedAction.getAttributeTypeMap = function () {
        return DeprecatedAction.attributeTypeMap;
    };
    DeprecatedAction.discriminator = 'kind';
    DeprecatedAction.attributeTypeMap = [
        {
            name: 'name',
            baseName: 'name',
            type: 'string',
        },
        {
            name: 'kind',
            baseName: 'kind',
            type: 'DeprecatedAction.KindEnum',
        },
        {
            name: 'title',
            baseName: 'title',
            type: 'string',
        },
        {
            name: 'subject',
            baseName: 'subject',
            type: 'string',
        },
        {
            name: 'body',
            baseName: 'body',
            type: 'string',
        },
        {
            name: 'addresses',
            baseName: 'addresses',
            type: 'Array<string>',
        },
        {
            name: 'htmlPart',
            baseName: 'htmlPart',
            type: 'string',
        },
        {
            name: 'subjectPart',
            baseName: 'subjectPart',
            type: 'string',
        },
        {
            name: 'textPart',
            baseName: 'textPart',
            type: 'string',
        },
        {
            name: 'templateName',
            baseName: 'templateName',
            type: 'string',
        },
        {
            name: 'webhookUrl',
            baseName: 'webhookUrl',
            type: 'string',
        },
        {
            name: 'message',
            baseName: 'message',
            type: 'string',
        },
        {
            name: 'topic',
            baseName: 'topic',
            type: 'string',
        },
    ];
    return DeprecatedAction;
}());
exports.DeprecatedAction = DeprecatedAction;
(function (DeprecatedAction) {
    var KindEnum;
    (function (KindEnum) {
        KindEnum[KindEnum["Webhook"] = 'webhook'] = "Webhook";
        KindEnum[KindEnum["Email"] = 'email'] = "Email";
        KindEnum[KindEnum["Sns"] = 'sns'] = "Sns";
    })(KindEnum = DeprecatedAction.KindEnum || (DeprecatedAction.KindEnum = {}));
})(DeprecatedAction = exports.DeprecatedAction || (exports.DeprecatedAction = {}));
exports.DeprecatedAction = DeprecatedAction;
//# sourceMappingURL=deprecatedAction.js.map