"use strict";
/**
 * Action Service
 * A service that receives incoming notifications and uses pre-defined templates (action objects) to turn those notifications into meaningful actions.
 *
 * OpenAPI spec version: v1beta2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var WebhookActionMutable = /** @class */ (function () {
    function WebhookActionMutable() {
    }
    WebhookActionMutable.getAttributeTypeMap = function () {
        return WebhookActionMutable.attributeTypeMap;
    };
    WebhookActionMutable.discriminator = undefined;
    WebhookActionMutable.attributeTypeMap = [
        {
            name: 'title',
            baseName: 'title',
            type: 'string',
        },
        {
            name: 'webhookUrl',
            baseName: 'webhookUrl',
            type: 'string',
        },
        {
            name: 'webhookPayload',
            baseName: 'webhookPayload',
            type: 'string',
        },
    ];
    return WebhookActionMutable;
}());
exports.WebhookActionMutable = WebhookActionMutable;
//# sourceMappingURL=webhookActionMutable.js.map