// tslint:disable
/**
 * Copyright 2022 Splunk, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"): you may
 * not use this file except in compliance with the License. You may obtain
 * a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 * Action Service
 * With the Action service in Splunk Cloud Services, you can receive incoming trigger events and use pre-defined action templates to turn these events into meaningful actions. 
 *
 * OpenAPI spec version: v1beta2.12 (recommended default)
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    RawJSONPayload,
    TriggerEventActionMetadata,
    TriggerEventKind,
} from './';

/**
 *
 * @export
 * @interface TriggerEvent
 */
export interface TriggerEvent {
    /**
     * 
     * @type {TriggerEventActionMetadata}
     * @memberof TriggerEvent
     */
    actionMetadata?: TriggerEventActionMetadata;

    /**
     * string-ified ISO-8601 date/time with zone.
     * @type {string}
     * @memberof TriggerEvent
     */
    readonly createdAt?: string;

    /**
     * The principal that generated the trigger event.
     * @type {string}
     * @memberof TriggerEvent
     */
    readonly createdBy?: string;

    /**
     * A unique identifier for this trigger event. Generated from a hash of all recursively-sorted event field values.
     * @type {string}
     * @memberof TriggerEvent
     */
    readonly id?: string;

    /**
     * 
     * @type {TriggerEventKind}
     * @memberof TriggerEvent
     */
    kind?: TriggerEventKind;

    /**
     * 
     * @type {RawJSONPayload}
     * @memberof TriggerEvent
     */
    payload?: RawJSONPayload;

    /**
     * The tenant within which the trigger event was generated.
     * @type {string}
     * @memberof TriggerEvent
     */
    readonly tenant?: string;

    /**
     * A description of the condition that caused the trigger event.
     * @type {string}
     * @memberof TriggerEvent
     */
    triggerCondition?: string;

    /**
     * The name of the trigger for which this event was created.
     * @type {string}
     * @memberof TriggerEvent
     */
    triggerName?: string;

    /**
     * A time to live (TTL), expressed as seconds after createdAt, after which the trigger event will no longer be acted upon.
     * @type {number}
     * @memberof TriggerEvent
     */
    ttlSeconds?: number;

}

